### ISSUE TITLE
 Screen Capture Fails Intermittently without VSync enabled

### ISSUE THREAD

**Issue by jcloutz-radix** [HeliosVirtualCockpit/Iris-Screen-Exporter#1]
Hello,

I would like to to suggest a change to the docs. In order for the server app to reliably capture the screen VSync should be enabled when using monitors with different refresh rates.

For the last couple of days I have been beating my head against the wall trying to figure out how why the remote display was flickering intermittently with a black screen. After a lot of googling, and a lot of trial and error I figured out it had to do with the refresh rates of the monitors i am using and DCS only respecting the refresh rate of my primary monitor.

I have a 2 display config:

1. 1440p @ 144hz (main game display)
2.  1680x1050 @ 60hz (secondary used for rendering MFD's

The game was rendering at 70'ish FPS and without vsync to limit it to the speed of the second monitor it was essentially missing frames which caused the captured display to render as a blank image and flicker.

**Comment by BlueFinBima** [comment]
@jcloutz-radix Jeremy, thanks for the issue and apologies for the delay.  I am not sure that many people read documentation these days, but this problem has been added to ours by https://github.com/HeliosVirtualCockpit/Iris-Screen-Exporter/commit/9463cc611a1527dd9ed2cd2d8b5013e351986ba0 and will appear in the minor release I am just about to publish.
