### ISSUE TITLE
Server throws error on start up

### ISSUE THREAD

**Issue by SRDMizzou** [HeliosVirtualCockpit/Iris-Screen-Exporter#13]
The server throws an error on start up (See attached error details and image). I tried both the 32 and 64 bit launchers and installed in both C and a different drive. Also ran as administrator. I can click continue after the fault but the server will not load the config file. I am running windows 11 and show no updates available for .NET. 

![iris error](https://github.com/HeliosVirtualCockpit/Iris-Screen-Exporter/assets/32020119/20428bda-7a18-4514-8860-1562bd751769)
[iris error.txt](https://github.com/HeliosVirtualCockpit/Iris-Screen-Exporter/files/13855407/iris.error.txt)

**Comment by BlueFinBima** [comment]
@SRDMizzou Thanks for reporting this.  Typically Iris is invoked from the command line with one of the options being the configuration file to be used.  Iris does ship with a dummy configuration file, but it is obviously not finding this file.

Please note that I updated the documentation (see `%programfiles%\Helios Virtual Cockpit\Iris Screen Exporter\Docs` ) which contains information on how to run Iris from the command line, as well as configuration topics.  `%programfiles%\Helios Virtual Cockpit\Iris Screen Exporter\Example Configurations\` contains what the folder indicates.

I'll tidy this up in the next release.

**Comment by BlueFinBima** [comment]
Fixed in 1.6.3 https://github.com/HeliosVirtualCockpit/Iris-Screen-Exporter/releases/latest
