### ISSUE TITLE
Enhancement: Linux Client

### ISSUE THREAD

**Issue by donoli1st** [HeliosVirtualCockpit/Iris-Screen-Exporter#2]
Hi
I'd like to run a client on a Raspberry Pi.
Would it be possible to describe me how the Images via UDP getting send?(MJPEG?) So that I can create a Linux Client to receive the image and show it on two screens, for example my MFD's..
Would this be possible?
If a Client could be realized I would distribute it to this GitHub if desired..
Thank you.

**Comment by BlueFinBima** [comment]
Hi @donoli1st, thanks for reaching out.  Iris uses 
<html>
<body>


CopyFromScreen(Int32, Int32, Int32, Int32, Size) | Performs a bit-block transfer of the color data, corresponding to a rectangle of pixels, from the screen to the drawing surface of the Graphics.
-- | --



</body>
</html>
from https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.copyfromscreen?view=dotnet-plat-ext-6.0

As far as I can tell, this is not compressed in any way.  A few years back, @damien022 successfully ran the client on RPi using mono if I recall correctly but I don't know the details.
UDP becomes a little problematic if the screen data size is greater than the packet size, but obviously there are ways around this.
I had thought that using an ffmpeg stream to replace iris, but I have not done the work to investigate much further but I can't see why this would not work, and would obviously work on RPi.
You might be interested in https://github.com/BlueFinBima/DCS-Helios-MFD which is a windows solution, and assuming you can find the tablets at a reasonable price, compares favourably (IMHO) to an RPi if you factor in the costs of the screen etc. 
If you develop your Iris Linux Client, it would be great if you could make it publicly available in some form.

**Comment by donoli1st** [comment]
Hi @BlueFinBima 
Thank you for your answer. It made a lot clear to me and I made a small python3 script which runs on a Raspberry. (Also on Windows)
I will polish the script a bit, but after that I would like to make it publicly available. Maybe, if I have some spare time, I will make another client in C++/#.. But the Pythonscript does it for me at the moment.

I've tried mono and it worked, more or less.. It couldn't find the iris.xml.. But possibly it will work..

I've done some research with C# and ffmpeg two months ago, to make a screencapturer. But it wasn't finished. The Screen capture worked and I had to make the Server part, but put it aside..
Again, thank you for your fast and accurate Support

**Comment by BlueFinBima** [comment]
Hi @donoli1st, I'm not sure why you'd create a c++ version if the python script works.  Do you think the script would perform adequately on a Pi Zero?  Thanks for explaining the paths you've explored thus far... very interesting.
Happy to link to your repo when your work is done, or discuss other options.

**Comment by BlueFinBima** [comment]
Hi @donoli1st, interested to know how you are getting on with this.  I did encounter a forum post which pointed at this https://github.com/bjanders/wxpython-iris-client which is a couple of years old now.  I have not investigated or tried this client, but seems interesting (as does yours).

**Comment by BlueFinBima** [comment]
With the option of the wxpython client, I think that there is really no reason for Iris to have a linux client.  Closing this.
